---
# tasks file for rhportal_reg

- name: Start fresh and unsubscribe to RHSM
  redhat_subscription:
    state: absent

- block:

  - name: Subscribe to RHSM using an activation key
    redhat_subscription:
      activationkey: "{{ rhsm_activation_key }}"
      force_register: yes
      org_id: "{{ rhsm_organization_id }}"
      state: present

  when: rhsm_activation_key and rhsm_state == "present"

- block:

  - name: Subscribe to RHSM using a username, password, and pool ID
    redhat_subscription:
      pool: "{{ rhsm_pool }}"
      password: "{{ rhsm_pw }}"
      username: "{{ rhsm_uname }}"
      force_register: yes
      state: present

  when: not rhsm_activation_key and rhsm_state == "present"

- block:

  - name: Reset repositories
    command: "subscription-manager repos --disable=*"

  - name: Setup repositories
    command: "subscription-manager repos --enable={{ item }}"
    with_items: "{{ rhsm_repo_list }}"

  - name: Cleanup yum repositories
    command: "yum clean all"
    args:
      warn: No

  when: rhsm_state == "present"

- name: Remove yum cache
  file:
    path: /var/cache/yum
    state: absent
