---
# tasks file for rhportal_reg

# This fails on RHEL 9
#- name: Start fresh and unsubscribe to RHSM
#  redhat_subscription:
#    state: absent

- name: Remove all subscriptions
  command: subscription-manager remove --all

- name: Unregister from the portal
  command: subscription-manager unregister
  ignore_errors: true

- name: Clean out configuration data
  command: subscription-manager clean

- block:

  - name: Subscribe to RHSM using an activation key
    redhat_subscription:
      activationkey: "{{ rhportal_reg_rhsm_activation_key }}"
      consumer_name: "{{ inventory_hostname }}"
      force_register: yes
      org_id: "{{ rhportal_reg_rhsm_organization_id }}"
      pool_ids: "{{ rhportal_reg_rhsm_pool_ids }}"
      state: present

  when: rhportal_reg_rhsm_activation_key and rhportal_reg_rhsm_state == "present"

- block:

  - name: Subscribe to RHSM using a username, password, and pool ID(s)
    redhat_subscription:
      consumer_name: "{{ inventory_hostname }}"
      pool_ids: "{{ rhportal_reg_rhsm_pool_ids }}"
      password: "{{ rhportal_reg_rhsm_pw }}"
      username: "{{ rhportal_reg_rhsm_uname }}"
      force_register: yes
      state: present

  when: not rhportal_reg_rhsm_activation_key and rhportal_reg_rhsm_state == "present"

- name: Define repositories to be enabled for RHEL 7
  set_fact:
    rhportal_reg_rhsm_repo_list:
      - rhel-7-server-rpms
  when: ansible_facts.distribution is defined and ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version is defined and ansible_facts.distribution_major_version == "7"

- name: Define repositories to be enabled for RHEL 8
  set_fact:
    rhportal_reg_rhsm_repo_list:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
  when: ansible_facts.distribution is defined and ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version is defined and ansible_facts.distribution_major_version == "8"

- name: Define repositories to be enabled for RHEL 9
  set_fact:
    rhportal_reg_rhsm_repo_list:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
  when: ansible_facts.distribution is defined and ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version is defined and ansible_facts.distribution_major_version == "9"

- name: Print default list of repositories to enable
  debug:
    var: rhportal_reg_rhsm_repo_list

- name: Add additional repositories to enable
  set_fact:
    rhportal_reg_rhsm_repo_list: "{{ rhportal_reg_rhsm_repo_list + rhportal_reg_rhsm_supplemental_repo_list }}"
  when: rhportal_reg_rhsm_supplemental_repo_list is defined

- name: Print full list of repositories to enable
  debug:
    var: rhportal_reg_rhsm_repo_list

- block:

  - name: Reset repositories
    command: "subscription-manager repos --disable=*"

  - name: Setup repositories
    command: "subscription-manager repos --enable={{ item }}"
    with_items: "{{ rhportal_reg_rhsm_repo_list }}"

  - name: Cleanup yum repositories
    command: "yum clean all"

  when: rhportal_reg_rhsm_state == "present"

- name: Remove yum cache
  file:
    path: /var/cache/yum
    state: absent
